# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/miniRV_clock.xdc

# XDC: new/miniRV_SoC.xdc

# IP: ip/IROM/IROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IROM || ORIG_REF_NAME==IROM} -quiet] -quiet
